### ISSUE TITLE
VeriphonePaymentForm. No virtual method getPublicKeyData()Lorg/bouncycastle/asn1/DERBitString

### ISSUE THREAD

**Issue by alexlarraga1** [verifoneone/verifone-ecom-android-sdk#2]
Error in VeriphonePaymentForm when click in pay button

```
java.lang.NoSuchMethodError: No virtual method getPublicKeyData()Lorg/bouncycastle/asn1/DERBitString; in class Lorg/bouncycastle/asn1/x509/SubjectPublicKeyInfo; or its super classes (declaration of 'org.bouncycastle.asn1.x509.SubjectPublicKeyInfo' appears in /data/data/mx.com.sfinx.aca.misaldo/code_cache/.overlay/base.apk/classes20.dex)
    at org.bouncycastle.openpgp.operator.jcajce.JcePublicKeyKeyEncryptionMethodGenerator.encryptSessionInfo(Unknown Source:188)
    at org.bouncycastle.openpgp.operator.PublicKeyKeyEncryptionMethodGenerator.generate(Unknown Source:16)
    at org.bouncycastle.openpgp.PGPEncryptedDataGenerator.open(Unknown Source:120)
    at org.bouncycastle.openpgp.PGPEncryptedDataGenerator.open(Unknown Source:1)
    at com.verifone.connectors.util.CardEncryption.encrypt(CardEncryption.kt:188)
    at com.verifone.connectors.util.CardEncryption.encryptionCard(CardEncryption.kt:84)
    at com.verifone.connectors.screens.CardFormScreen.onCreateView$lambda-2(CardFormScreen.kt:249)
    at com.verifone.connectors.screens.CardFormScreen.$r8$lambda$B6H_mEvulSlkpY8b7-wSjNZxIY8(Unknown Source:0)
    at com.verifone.connectors.screens.CardFormScreen$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
    at android.view.View.performClick(View.java:7558)
    at android.view.View.performClickInternal(View.java:7534)
    at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
    at android.view.View$PerformClick.run(View.java:29661)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:240)
    at android.os.Looper.loop(Looper.java:351)
    at android.app.ActivityThread.main(ActivityThread.java:8381)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

**Comment by alexlarraga1** [comment]
Same in function `VerifonePaymentForm.encryptCardData`

**Comment by craigchristenson** [comment]
Hi thanks for reporting the issue. Can you tell me what version of bouncy castle bcpg-jdk15on you are using?

**Comment by alexlarraga1** [comment]
Hi craig 

Im using the version  `1.57` according the docs

**Comment by craigchristenson** [comment]
I tested with a fresh android app and still was not able to replicate. Can you try cloning [this example app](https://github.com/craigchristenson/ExampleApp), updating the examplePublicKey in the MainActivity class to your own and running it? You should see an encrypted card in Logcat.

**Comment by alexlarraga1** [comment]
It's a dependency error, another library uses `org.bouncycastle:bcpkix-jdk15on:1.70` and causes the error, downgrading the version to `org.bouncycastle:bcpkix-jdk15on:1.57` fixes it
